### ISSUE TITLE
How to download Moving MNIST dataset for training?

### ISSUE THREAD

**Issue by mangalp** [voletiv/mcvd-pytorch#1]
Dear authors, 

The README says that ``The script will automatically download the PyTorch MNIST dataset, which will be used to generate Stochastic Moving MNIST dynamically`` but doesn't mention which script is supposed to do this. Can you please edit the README with the information? 

Thank you.

**Comment by voletiv** [comment]
When you run the training/sampling on it, the dataset will be automatically downloaded by the dataset class : https://github.com/voletiv/mcvd-pytorch/blob/d10f52334db554a4379ff9eb798c249bc144290d/datasets/stochastic_moving_mnist.py#L43
