### ISSUE TITLE
Are metrics on your 2D convolution MCVD model?

### ISSUE THREAD

**Issue by JunyaoHu** [voletiv/mcvd-pytorch#15]
Hi, dear author!

>Our MCVD models are built from simple non-recurrent **2D-convolutional** architectures, conditioning on blocks of frames and generating blocks of frames. We generate videos of arbitrary lengths autoregressively in a block-wise manner.

you mention you use `conv2d` to solve the problem, and you show the FVD of the model. But your code has many modes of model, like `ncsn`, `unet`, `unetmore`, `unetmore3d`. I want to know which mode makes the FVD on your paper.

```
def get_model(config):
    version = getattr(config.model, 'version', 'SMLD').upper()
    arch = getattr(config.model, 'arch', 'ncsn')
    depth = getattr(config.model, 'depth', 'deep')
    if arch == 'unetmore':
        from models.better.ncsnpp_more import UNetMore_DDPM # This lets the code run on CPU when 'unetmore' is not used
        return UNetMore_DDPM(config).to(config.device)#.to(memory_format=torch.channels_last).to(config.device)
    elif arch in ['unetmore3d', 'unetmorepseudo3d']:
        from models.better.ncsnpp_more import UNetMore_DDPM # This lets the code run on CPU when 'unetmore' is not used
        # return UNetMore_DDPM(config).to(memory_format=torch.channels_last_3d).to(config.device) # channels_last_3d doesn't work!
        return UNetMore_DDPM(config).to(config.device)#.to(memory_format=torch.channels_last).to(config.device)
    else:
        Exception("arch is not valid [ncsn, unet, unetmore, unetmore3d]")
```
in your code [/example_scripts/final/training_scripts.sh](https://github.com/voletiv/mcvd-pytorch/blob/master/example_scripts/final/training_scripts.sh) ,  i find their mode are all  
`arch='unetmore'` and it use `NCSNpp` model, so i am not sure your result is on **2D convolution or 3D convolution**?

like 
```
# Video prediction non-spade
export exp="smmnist_big_5c5_unetm_b2"
export config_mod="training.snapshot_freq=50000 sampling.subsample=100 sampling.clip_before=True sampling.max_data_iter=1 model.version=DDPM model.arch=unetmore model.num_res_blocks=2"
sh ./example_scripts/final/base_1f.sh
```

and in `NCSNpp` you use `layers3d` , it is based on `Conv3d`. 
```
class NCSNpp(nn.Module):
  """NCSN++ model"""
  def __init__(self, config):
    super().__init__()
    self.config = config
    self.act = act = get_act(config)
    self.register_buffer('sigmas', get_sigmas(config))
    self.is3d = (config.model.arch in ["unetmore3d", "unetmorepseudo3d"])
    self.pseudo3d = (config.model.arch == "unetmorepseudo3d")
    if self.is3d:
      from . import layers3d
```

**Comment by AlexiaJM** [comment]
Hi, we use unetmore which is 2d, there is unetmorepseudo3d and unetmore3d but we do not use those (we only experimented with them in the past). Since is3d=False and pseudo3d=False, it relies on 2d 3x3 convolutions, see https://github.com/voletiv/mcvd-pytorch/blob/451da2eb635bad50da6a7c03b443a34c6eb08b3a/models/better/ncsnpp_more.py#L108.
