### ISSUE TITLE
how much is your sampling.batch_size？

### ISSUE THREAD

**Issue by JunyaoHu** [voletiv/mcvd-pytorch#16]
hi, I notice that you set ` sampling.batch_size=100/200` in `sampling_scripts.sh` on SMMNIST/KTH dataset but your paper reads ` averaged across 256 test videos` and `on 256 test videos`, so it means batch_size should be 256? thanks again!
![image](https://user-images.githubusercontent.com/67564714/217315357-df31f263-ebe3-44ec-8a18-c67cd7643a19.png)

https://github.com/voletiv/mcvd-pytorch/blob/451da2eb635bad50da6a7c03b443a34c6eb08b3a/example_scripts/final/sampling_scripts.sh#L47

https://github.com/voletiv/mcvd-pytorch/blob/451da2eb635bad50da6a7c03b443a34c6eb08b3a/example_scripts/final/sampling_scripts.sh#L108

**Comment by AlexiaJM** [comment]
Hi @JunyaoHu, the batch-size does not matter, it will still do 256 images (200, then 56 if batch-size=200).

**Comment by JunyaoHu** [comment]
I understand, test dataset length is 256, thanks! silly me lol
