### ISSUE TITLE
KTH dataset content question

### ISSUE THREAD

**Issue by yptang5488** [voletiv/mcvd-pytorch#17]
Hi, I use `gdown --fuzzy https://drive.google.com/file/d/1d2UfHV6RhSrwdDAlCFY3GymtFPpmh_8X/view?usp=sharing` to download KTH64 dataset. When I run the code `dataset, test_dataset = get_dataset(DATA_PATH, config, video_frames_pred=config.data.num_frames)` I got an KeyError. 

![Screenshot from 2023-02-10 16-19-06](https://user-images.githubusercontent.com/60002415/218044418-a5caa565-7537-4dab-8018-118a0dd069a8.png)

I found that the file _persons.pkl_ is empty (5 bytes and only `{}`). I would like to confirm with you about the dataset if it is all right. Thanks!

**Comment by AlexiaJM** [comment]
I'm not sure why gdown fail, but the error says to big and its indeed very big; since it doesn't work, you can instead download it manually by following the link on your browser, its 13Gb.

https://drive.google.com/u/0/uc?id=1-R_srAOy5ZcylGXVernqE4WLCe6N4_wq&export=download
