### ISSUE TITLE
Error training for KTH64

### ISSUE THREAD

**Issue by mangalp** [voletiv/mcvd-pytorch#2]
Dear authors,

I am unable to run the provided training script for KTH64. I downloaded the dataset from `gdown --fuzzy https://drive.google.com/file/d/1d2UfHV6RhSrwdDAlCFY3GymtFPpmh_8X/view?usp=sharing` as instructed and unzipped it. I tried running the training with the following command `CUDA_VISIBLE_DEVICES=0 python main.py --config configs/kth64.yml --data_path Data/KTH64/KTH64_h5 --exp smmnist_cat --ni`. However, I end up with the error shown in the attached screenshot. Can you please suggest what is the issue and how to fix it? 

Thank you.

<img width="1049" alt="Screenshot 2022-06-01 at 19 16 27" src="https://user-images.githubusercontent.com/31291854/171474387-eab6c2c2-61ee-46ac-b526-4a6b0da5d94c.png">

**Comment by voletiv** [comment]
Thanks for pointing this out! Please try with the config file `kth64_big.yml`, that should solve this. `kth64.yml` is an older file, we've deleted it from the repo now.
