### ISSUE TITLE
Usage for brand new private videos

### ISSUE THREAD

**Issue by IoSonoMarco** [voletiv/mcvd-pytorch#24]
Any recommended checkpoint or strategy to just try to predict the next frames of a brand new video, without training from scratch?

**Comment by AlexiaJM** [comment]
You could try to implement LoRA, its very popular for fine-tuning both LLMs and Stable-Diffusion. I guess you could use the cityscape model as pre-trained model, it depends on your applications. We have no code for fine-tuning though.

**Comment by IoSonoMarco** [comment]
Oh I was actually wondering whether it would have worked on a video out of the box. Like it is a pre-trained model that can work everywhere without fine-tuning at some baseline performance level

**Comment by AlexiaJM** [comment]
No, this one is trained on specific datasets. You should try looking for text-to-videos models. This way you could prompt the model to get what you want.

**Comment by IoSonoMarco** [comment]
ok thanks :)
