### ISSUE TITLE
what is the `average FVD`?

### ISSUE THREAD

**Issue by JunyaoHu** [voletiv/mcvd-pytorch#25]
In table 1 of your paper, what is the `average FVD`? Is it avg_fvd? or fvd_traj_mean?

![image](https://github.com/voletiv/mcvd-pytorch/assets/67564714/b626a86b-9897-4627-b5ff-757d5276ee49)

https://github.com/voletiv/mcvd-pytorch/blob/451da2eb635bad50da6a7c03b443a34c6eb08b3a/runners/ncsn_runner.py#L2217-L2229C20

```
        def fvd_stuff(fake_embeddings, real_embeddings):
            avg_fvd = frechet_distance(fake_embeddings, real_embeddings)
            if preds_per_test > 1:
                fvds_list = []
                # Calc FVD for 5 random trajs (each), and average that FVD
                trajs = np.random.choice(np.arange(preds_per_test), (preds_per_test,), replace=False)
                for traj in trajs:
                    fvds_list.append(frechet_distance(fake_embeddings[traj::preds_per_test], real_embeddings))
                fvd_traj_mean, fvd_traj_std  = float(np.mean(fvds_list)), float(np.std(fvds_list))
                fvd_traj_conf95 = fvd_traj_mean - float(st.norm.interval(alpha=0.95, loc=fvd_traj_mean, scale=st.sem(fvds_list))[0])
            else:
                fvd_traj_mean, fvd_traj_std, fvd_traj_conf95 = -1, -1, -1
            return avg_fvd, fvd_traj_mean, fvd_traj_std, fvd_traj_conf95
```

**Comment by AlexiaJM** [comment]
For each 5 start frames, we generate 10 videos. We calculate the FVD for each of the 10 videos and take the average. We calculate the SSIM for all 10 videos and take the max value (i.e., the closest of the 10 videos to the real video). 

There are 256 test videos, which we use their 5 start frames. We average max-SSIM and avg-FVD over the 256 test videos.

**Comment by AlexiaJM** [comment]
Should be fvd_traj_mean

**Comment by JunyaoHu** [comment]
Thanks

**Comment by AlexiaJM** [comment]
and the variable you asked should be "fvd_traj_mean" since its averaging twice.

**Comment by JunyaoHu** [comment]
Hello, are the other datasets also calculating the mean of FVD, the same as SMMNIST?
